### ISSUE TITLE
redundent code benchmark_index

### ISSUE THREAD

**Issue by krushnapavan9** [Svvord/iMAP#4]
There is a redundant code in the benchmark_index.R  at  line 71

> 70    NNs_c = cell_type[i]
> 71     NNs_i = NNs_c == cell_type[i]
> 72     NNs_ = NNs_[NNs_i]

in the above code, NNs_i will always return true

**Comment by Svvord** [comment]
Thanks for pointing this out. According to our original description, the line 70 should be NNs_c = cell_type[NNs_]. However, in our following application, we found this constraint is too strict resulting in various numbers of neighbors for cells from the same dataset (i.e. from 0.5*k to k), and as the implementation of Harmony’s iLISI index, we then just consider the mixture of cells from different batches, ignoring their cell type identity. Because the condition falseRates[i] < 0.5 only retains those cells surrounding with cells from their own cell type, we think this modification is reasonable. We also revise our codes to make this as an adjustable parameter.
